In [1]:
import numpy as np

# 1d array

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.ndim

1

# 2d array

In [11]:
dim2 = np.array([[1,2,3,4],[5,6,7,8]])

In [12]:
dim2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
dim2.dtype

dtype('int32')

In [14]:
type(dim2)

numpy.ndarray

In [15]:
dim2.ndim

2

In [16]:
for x in dim2:
    print(x)

[1 2 3 4]
[5 6 7 8]


In [18]:
for x in dim2:
    print(x)
    for y in x:
        print(y)

[1 2 3 4]
1
2
3
4
[5 6 7 8]
5
6
7
8


In [21]:
# get second element in second row -- returns 6
dim2[1,1]

6

In [22]:
# get third element in first row -- returns 3
dim2[0,2]

3

# 2d expanded

In [23]:
dim2x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [24]:
dim2x.ndim

2

In [26]:
for x in dim2x:
    print(x)
    print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>
[5 6 7 8]
<class 'numpy.ndarray'>
[ 9 10 11 12]
<class 'numpy.ndarray'>


In [27]:
for x in dim2x:
    print(x)
    for y in x:
        print(y)

[1 2 3 4]
1
2
3
4
[5 6 7 8]
5
6
7
8
[ 9 10 11 12]
9
10
11
12


In [28]:
# get third row, 3rd element - returns 11
dim2x[2,2]

11

In [29]:
# get second row 4th element - returns 8
dim2x[1,3]

8

# 3d array

In [30]:
dim3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [31]:
dim3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [32]:
type(dim3)

numpy.ndarray

In [33]:
dim3.ndim

3

In [35]:
for x in dim3:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [36]:
for x in dim3:
    for y in x:
        print(y)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [39]:
for x in dim3:
    print('1: ',x)
    for y in x:
        print('2: ',y)
        for z in y:
            print('3: ',z)

1:  [[1 2 3]
 [4 5 6]]
2:  [1 2 3]
3:  1
3:  2
3:  3
2:  [4 5 6]
3:  4
3:  5
3:  6
1:  [[ 7  8  9]
 [10 11 12]]
2:  [7 8 9]
3:  7
3:  8
3:  9
2:  [10 11 12]
3:  10
3:  11
3:  12


In [41]:
for x in np.nditer(dim3):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
