In [1]:
import numpy as np

# 1 dim array

In [2]:
mylist = [1,2,3,4]

In [3]:
type(mylist)

list

In [4]:
myarr = np.array(mylist)

In [5]:
type(myarr)

numpy.ndarray

In [6]:
myarr

array([1, 2, 3, 4])

In [7]:
myarr.ndim

1

In [16]:
for x in myarr:
    print(x)

1
2
3
4


# 2 dim array

In [8]:
mylist2 = [[1,2,3],[4,5,6,],[7,8,9]]

In [9]:
type(mylist2)

list

In [12]:
myarr2 = np.array(mylist2)

In [13]:
type(myarr2)

numpy.ndarray

In [14]:
myarr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
myarr2.ndim

2

In [19]:
for x in myarr2:
    print(x)
    print(type(x))
    print(x.ndim)

[1 2 3]
<class 'numpy.ndarray'>
1
[4 5 6]
<class 'numpy.ndarray'>
1
[7 8 9]
<class 'numpy.ndarray'>
1


In [21]:
for x in myarr2:
    print(x)
    for y in x:
        print(y)

[1 2 3]
1
2
3
[4 5 6]
4
5
6
[7 8 9]
7
8
9


In [23]:
for x in np.nditer(myarr2):  # flattens the array
    print(x)

1
2
3
4
5
6
7
8
9


# 3 dim array

In [24]:
mylist3 = [ [[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]], [[13,14,15],[16,17,18]] ]

In [25]:
type(mylist3)

list

In [26]:
for x in mylist3:
    print(x)

[[1, 2, 3], [4, 5, 6]]
[[7, 8, 9], [10, 11, 12]]
[[13, 14, 15], [16, 17, 18]]


In [28]:
for x in mylist3:
    print(x)
    for y in x:
        print(y)
        for z in y:
            print(z)

[[1, 2, 3], [4, 5, 6]]
[1, 2, 3]
1
2
3
[4, 5, 6]
4
5
6
[[7, 8, 9], [10, 11, 12]]
[7, 8, 9]
7
8
9
[10, 11, 12]
10
11
12
[[13, 14, 15], [16, 17, 18]]
[13, 14, 15]
13
14
15
[16, 17, 18]
16
17
18


In [29]:
myarr3 = np.array(mylist3)

In [30]:
myarr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [31]:
myarr3.ndim

3

In [32]:
type(myarr3)

numpy.ndarray

# 4d array

In [39]:
mylist4 = [ [[[1,2],[3,4]], [[4,5],[6,7]]], [[[7,8],[9,10]],[[10,11],[12,13]]], [[[14,15],[16,17]],[[18,19],[20,21]]] ]

In [40]:
myarr4 = np.array(mylist4)

In [41]:
myarr4.ndim

4

In [43]:
for a in myarr4:
    print(a)

[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]
[[[ 7  8]
  [ 9 10]]

 [[10 11]
  [12 13]]]
[[[14 15]
  [16 17]]

 [[18 19]
  [20 21]]]


In [47]:
for a in myarr4:
    print(a)
    for b in a:
        print(b)
        for c in b:
            print(c)
            for d in c:
                print(d)

[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]
[[1 2]
 [3 4]]
[1 2]
1
2
[3 4]
3
4
[[4 5]
 [6 7]]
[4 5]
4
5
[6 7]
6
7
[[[ 7  8]
  [ 9 10]]

 [[10 11]
  [12 13]]]
[[ 7  8]
 [ 9 10]]
[7 8]
7
8
[ 9 10]
9
10
[[10 11]
 [12 13]]
[10 11]
10
11
[12 13]
12
13
[[[14 15]
  [16 17]]

 [[18 19]
  [20 21]]]
[[14 15]
 [16 17]]
[14 15]
14
15
[16 17]
16
17
[[18 19]
 [20 21]]
[18 19]
18
19
[20 21]
20
21


In [49]:
# flatten the 4d array
for i in np.nditer(myarr4):
    print(i)

1
2
3
4
4
5
6
7
7
8
9
10
10
11
12
13
14
15
16
17
18
19
20
21
